"""Exhaustive LinuxCNC G-code and M-code reference data.

Complete list of all valid codes supported by LinuxCNC's RS274NGC interpreter.
Each entry: (code, modal_group, description, example)

Sources: LinuxCNC documentation (linuxcnc.org/docs/stable/html/gcode/)
Content rephrased for compliance with licensing restrictions.
"""

from typing import List, Tuple

# (code, group/category, description, example_code)
GCodeEntry = Tuple[str, str, str, str]

G_CODES: List[GCodeEntry] = [
    # --- Motion (Modal Group 1) ---
    ("G0", "Motion", "Rapid positioning — moves at maximum speed, no cutting",
     "G0 X2.0 Z0.1  (rapid to safe position)"),
    ("G1", "Motion", "Linear interpolation — straight-line cutting move at feed rate",
     "G1 X1.5 Z-1.0 F0.005  (turn OD to 1.5\" dia)"),
    ("G2", "Motion", "Circular interpolation clockwise — arc move CW",
     "G2 X1.0 Z-0.5 I-0.25 K0.0 F0.003  (CW arc to X1 Z-0.5)"),
    ("G3", "Motion", "Circular interpolation counter-clockwise — arc move CCW",
     "G3 X1.0 Z-0.5 I0.0 K-0.25 F0.003  (CCW arc to X1 Z-0.5)"),
    ("G4", "Dwell", "Dwell — pause for P seconds (or P milliseconds if integer)",
     "G4 P0.5  (dwell 0.5 seconds for spring pass)"),
    ("G5", "Motion", "Cubic spline — smooth curve through control points",
     "G5 X1.0 Z-1.0 I0.2 J-0.1 P0.3 Q-0.2"),
    ("G5.1", "Motion", "Quadratic B-spline — smooth curve interpolation",
     "G5.1 X1.0 Z-0.5 I0.5 K-0.25"),
    ("G5.2", "Motion", "NURBS block start — begin NURBS curve definition",
     "G5.2\nX0.5 Z-0.2 P1\nX1.0 Z-0.5 P1\nG5.3"),
    ("G5.3", "Motion", "NURBS block end — end NURBS curve definition",
     "(see G5.2 example)"),
    ("G7", "Diameter/Radius", "Lathe diameter mode — X values are diameters",
     "G7  (X1.0 means 1.0\" diameter)"),
    ("G8", "Diameter/Radius", "Lathe radius mode — X values are radii",
     "G8  (X1.0 means 1.0\" radius = 2.0\" diameter)"),
    ("G10 L1", "Tool/WCS Setup", "Set tool table entry — define tool offsets",
     "G10 L1 P1 X0.0 Z-1.234 R0.032  (set tool 1 offsets)"),
    ("G10 L2", "Tool/WCS Setup", "Set coordinate system origin — absolute values",
     "G10 L2 P1 X0.0 Z0.0  (set G54 origin to machine zero)"),
    ("G10 L10", "Tool/WCS Setup", "Set tool table, calculated from current position",
     "G10 L10 P2 X1.5 Z0.0  (tool 2: current pos = X1.5 Z0)"),
    ("G10 L11", "Tool/WCS Setup", "Set tool table, calculated from workpiece position",
     "G10 L11 P3 X2.0 Z0.0  (tool 3 offset from workpiece)"),
    ("G10 L20", "Tool/WCS Setup", "Set coordinate system origin from current position",
     "G10 L20 P1 X2.0 Z0.0  (touch-off: here is X2.0 Z0.0)"),
    ("G17", "Plane Select", "XY plane selection (default for mills)",
     "G17  (arcs in XY plane, Z is normal)"),
    ("G17.1", "Plane Select", "UV plane selection",
     "G17.1  (arcs in UV plane)"),
    ("G18", "Plane Select", "XZ plane selection (default for lathes)",
     "G18  (arcs in XZ plane — standard lathe mode)"),
    ("G18.1", "Plane Select", "UW plane selection",
     "G18.1  (arcs in UW plane)"),
    ("G19", "Plane Select", "YZ plane selection",
     "G19  (arcs in YZ plane)"),
    ("G19.1", "Plane Select", "VW plane selection",
     "G19.1  (arcs in VW plane)"),
    ("G20", "Units", "Inch mode — all values interpreted as inches",
     "G20  (all subsequent values in inches)"),
    ("G21", "Units", "Millimeter mode — all values interpreted as mm",
     "G21  (all subsequent values in millimeters)"),
    ("G28", "Return", "Return to home position through optional intermediate point",
     "G28 Z0.1  (retract Z to 0.1 then go home)"),
    ("G28.1", "Return", "Store current absolute position as home position",
     "G28.1  (save current position as G28 target)"),
    ("G30", "Return", "Return to second home position through optional intermediate",
     "G30 Z0.1  (go to second home via Z0.1)"),
    ("G30.1", "Return", "Store current absolute position as second home position",
     "G30.1  (save current position as G30 target)"),
    ("G33", "Motion", "Spindle-synchronized motion — threading move",
     "G33 Z-1.0 K0.05  (thread at 0.050\" pitch, 20 TPI)"),
    ("G33.1", "Motion", "Rigid tapping — synchronized tap cycle",
     "G33.1 Z-0.5 K0.05  (rigid tap 0.5\" deep, 20 TPI)"),
    ("G38.2", "Probing", "Probe toward workpiece, stop on contact, signal error if no contact",
     "G38.2 Z-1.0 F5.0  (probe down, error if no touch)"),
    ("G38.3", "Probing", "Probe toward workpiece, stop on contact, no error if no contact",
     "G38.3 Z-1.0 F5.0  (probe down, no error on miss)"),
    ("G38.4", "Probing", "Probe away from workpiece, stop on loss of contact, signal error",
     "G38.4 Z1.0 F5.0  (probe away, error if no release)"),
    ("G38.5", "Probing", "Probe away from workpiece, stop on loss of contact, no error",
     "G38.5 Z1.0 F5.0  (probe away, no error on miss)"),
    ("G40", "Cutter Comp", "Cancel cutter radius compensation",
     "G40  (cancel comp before tool change)"),
    ("G41", "Cutter Comp", "Cutter compensation left — tool offset to left of path",
     "G41 D1  (comp left using tool 1 diameter)"),
    ("G41.1", "Cutter Comp", "Dynamic cutter compensation left — D word specifies diameter",
     "G41.1 D0.064  (comp left, 0.032\" radius)"),
    ("G42", "Cutter Comp", "Cutter compensation right — tool offset to right of path",
     "G42 D1  (comp right using tool 1 diameter)"),
    ("G42.1", "Cutter Comp", "Dynamic cutter compensation right — D word specifies diameter",
     "G42.1 D0.064  (comp right, 0.032\" radius)"),
    ("G43", "Tool Length", "Apply tool length offset from tool table (H word)",
     "G43 H1  (apply tool 1 length offset)\nG43  (apply current tool offset)"),
    ("G43.1", "Tool Length", "Dynamic tool length offset — values from axis words",
     "G43.1 Z-1.234  (set tool offset to -1.234\")"),
    ("G43.2", "Tool Length", "Apply tool length offset for additional tool (lathe)",
     "G43.2 H2  (apply tool 2 offset additionally)"),
    ("G49", "Tool Length", "Cancel tool length offset",
     "G49  (remove all tool length offsets)"),
    ("G52", "Coordinate", "Local coordinate system offset (temporary shift)",
     "G52 X0.5 Z-0.25  (shift origin by X0.5 Z-0.25)"),
    ("G53", "Coordinate", "Move in machine coordinates (non-modal, one line only)",
     "G53 G0 X0.0 Z0.0  (rapid to machine home)"),
    ("G54", "Coordinate", "Select work coordinate system 1 (default)",
     "G54  (use WCS 1 — most common)"),
    ("G55", "Coordinate", "Select work coordinate system 2",
     "G55  (switch to WCS 2 for second setup)"),
    ("G56", "Coordinate", "Select work coordinate system 3",
     "G56  (switch to WCS 3)"),
    ("G57", "Coordinate", "Select work coordinate system 4",
     "G57  (switch to WCS 4)"),
    ("G58", "Coordinate", "Select work coordinate system 5",
     "G58  (switch to WCS 5)"),
    ("G59", "Coordinate", "Select work coordinate system 6",
     "G59  (switch to WCS 6)"),
    ("G59.1", "Coordinate", "Select work coordinate system 7",
     "G59.1  (switch to WCS 7)"),
    ("G59.2", "Coordinate", "Select work coordinate system 8",
     "G59.2  (switch to WCS 8)"),
    ("G59.3", "Coordinate", "Select work coordinate system 9",
     "G59.3  (switch to WCS 9)"),
    ("G61", "Path Control", "Exact path mode — machine stops at each programmed point",
     "G61  (full stop at every corner — slowest)"),
    ("G61.1", "Path Control", "Exact stop mode — decelerate to stop at each point",
     "G61.1  (decel to zero at each point)"),
    ("G64", "Path Control", "Blending mode with optional tolerance (P) and naive cam (Q)",
     "G64 P0.001 Q0.001  (blend within 0.001\" tolerance)"),
    ("G73", "Canned Cycles", "Drilling cycle with chip breaking — peck with retract",
     "G73 Z-0.5 Q0.1 R0.1 F5.0  (peck 0.1\" deep)"),
    ("G76", "Canned Cycles", "Threading cycle (lathe) — multi-pass thread cutting",
     "G76 P010060 Z-1.0 I-0.032 J0.005 K0.032  (20 TPI external)"),
    ("G80", "Canned Cycles", "Cancel canned cycle — return to normal motion",
     "G80  (cancel any active canned cycle)"),
    ("G81", "Canned Cycles", "Drilling cycle — drill to depth, rapid out",
     "G81 Z-0.5 R0.1 F5.0  (drill 0.5\" deep)"),
    ("G82", "Canned Cycles", "Drilling cycle with dwell — drill, dwell at bottom, rapid out",
     "G82 Z-0.5 R0.1 P0.5 F5.0  (drill, dwell 0.5s)"),
    ("G83", "Canned Cycles", "Peck drilling cycle — deep hole with full retract pecks",
     "G83 Z-2.0 Q0.25 R0.1 F3.0  (peck 0.25\" per pass)"),
    ("G84", "Canned Cycles", "Right-hand tapping cycle",
     "G84 Z-0.75 R0.1 F0.05  (tap 3/4\" deep, 20 TPI)"),
    ("G85", "Canned Cycles", "Boring cycle — bore to depth, feed out",
     "G85 Z-1.0 R0.1 F2.0  (bore 1\" deep, feed retract)"),
    ("G86", "Canned Cycles", "Boring cycle — bore to depth, spindle stop, rapid out",
     "G86 Z-1.0 R0.1 F2.0  (bore, stop spindle, rapid out)"),
    ("G87", "Canned Cycles", "Back boring cycle",
     "G87 Z-1.0 R0.1 F2.0  (back bore)"),
    ("G88", "Canned Cycles", "Boring cycle — bore to depth, dwell, manual retract",
     "G88 Z-1.0 R0.1 P1.0 F2.0  (bore, dwell, manual out)"),
    ("G89", "Canned Cycles", "Boring cycle — bore to depth, dwell, feed out",
     "G89 Z-1.0 R0.1 P0.5 F2.0  (bore, dwell 0.5s, feed out)"),
    ("G90", "Distance Mode", "Absolute distance mode — coordinates are absolute positions",
     "G90\nG1 X1.0 Z-0.5  (move to absolute X1.0 Z-0.5)"),
    ("G90.1", "Distance Mode", "Absolute arc distance mode — I/J/K are absolute",
     "G90.1  (arc centers given as absolute coords)"),
    ("G91", "Distance Mode", "Incremental distance mode — coordinates are relative",
     "G91\nG1 Z-0.1  (move 0.1\" in -Z direction)"),
    ("G91.1", "Distance Mode", "Incremental arc distance mode — I/J/K are relative (default)",
     "G91.1  (arc centers relative to start — default)"),
    ("G92", "Coordinate", "Coordinate system offset — shift all coordinate systems",
     "G92 X2.0 Z0.0  (set current position as X2 Z0)"),
    ("G92.1", "Coordinate", "Cancel G92 offset and reset parameters to zero",
     "G92.1  (clear G92 offset completely)"),
    ("G92.2", "Coordinate", "Cancel G92 offset but keep parameters stored",
     "G92.2  (deactivate G92 but remember values)"),
    ("G92.3", "Coordinate", "Restore G92 offset from parameters",
     "G92.3  (re-apply previously stored G92 offset)"),
    ("G93", "Feed Mode", "Inverse time feed mode — F word is moves per minute",
     "G93\nG1 X1.0 Z-0.5 F2.0  (complete move in 0.5 min)"),
    ("G94", "Feed Mode", "Units per minute feed mode — F is inches/min or mm/min",
     "G94\nG1 Z-1.0 F10.0  (feed at 10 inches per minute)"),
    ("G95", "Feed Mode", "Units per revolution feed mode — F is inches/rev or mm/rev",
     "G95\nG1 X1.5 F0.005  (0.005\" per spindle revolution)"),
    ("G96", "Spindle Mode", "Constant surface speed (CSS) — S is surface ft/min or m/min",
     "G96 S400 D2000  (400 SFM, max 2000 RPM clamp)"),
    ("G97", "Spindle Mode", "RPM mode — S is spindle revolutions per minute",
     "G97 S800  (fixed 800 RPM regardless of diameter)"),
    ("G98", "Canned Cycles", "Canned cycle return to initial Z level",
     "G98  (retract to Z level before cycle started)"),
    ("G99", "Canned Cycles", "Canned cycle return to R level",
     "G99  (retract only to R level between holes)"),
]

M_CODES: List[GCodeEntry] = [
    # --- Program Control ---
    ("M0", "Program Control", "Program pause — execution stops, operator must resume",
     "G1 X1.0 F0.005\nM0  (pause for measurement check)"),
    ("M1", "Program Control", "Optional stop — pauses only if optional stop switch is ON",
     "G1 Z-1.0 F0.005\nM1  (optional pause between passes)"),
    ("M2", "Program Control", "Program end — resets to defaults, rewinds",
     "G0 X2.0 Z0.1\nM2  (end program)"),
    ("M30", "Program Control", "Program end and rewind — same as M2 with pallet shuttle",
     "G0 X2.0 Z0.1\nM30  (end and rewind to start)"),
    ("M60", "Program Control", "Pallet shuttle and program pause",
     "M60  (shuttle pallet and pause)"),
    # --- Spindle ---
    ("M3", "Spindle", "Spindle on clockwise (forward) at S speed",
     "M3 S800  (spindle forward at 800 RPM)"),
    ("M4", "Spindle", "Spindle on counter-clockwise (reverse) at S speed",
     "M4 S500  (spindle reverse at 500 RPM)"),
    ("M5", "Spindle", "Spindle stop",
     "M5  (stop spindle rotation)"),
    ("M19", "Spindle", "Orient spindle — rotate to specific position and lock",
     "M19 R90  (orient spindle to 90 degrees)"),
    # --- Coolant ---
    ("M7", "Coolant", "Mist coolant on",
     "M7  (turn on mist coolant)"),
    ("M8", "Coolant", "Flood coolant on",
     "M8  (turn on flood coolant)"),
    ("M9", "Coolant", "All coolant off",
     "M9  (turn off all coolant)"),
    # --- Tool Change ---
    ("M6", "Tool Change", "Tool change — execute tool change to selected tool (Tn)",
     "T0202 M6  (select tool 2, offset 2, change)\nG43  (apply tool offset)"),
    ("M61", "Tool Change", "Set current tool number — change tool number without motion",
     "M61 Q3  (tell system current tool is T3)"),
    # --- Overrides ---
    ("M48", "Overrides", "Enable feed and spindle overrides",
     "M48  (allow operator override knobs to work)"),
    ("M49", "Overrides", "Disable feed and spindle overrides",
     "M49  (lock out override knobs — run at programmed rate)"),
    ("M50", "Overrides", "Feed override control — P0 disable, P1 enable",
     "M50 P0  (disable feed override)\nM50 P1  (re-enable)"),
    ("M51", "Overrides", "Spindle override control — P0 disable, P1 enable",
     "M51 P0  (disable spindle override)"),
    ("M52", "Overrides", "Adaptive feed control — P0 disable, P1 enable",
     "M52 P1  (enable adaptive feed from motion.adaptive-feed)"),
    ("M53", "Overrides", "Feed stop control — P0 disable, P1 enable",
     "M53 P1  (enable feed stop/hold input)"),
    # --- I/O Control ---
    ("M62", "Digital I/O", "Turn on digital output synchronized with motion (P word)",
     "M62 P0  (turn on output 0 at next motion start)"),
    ("M63", "Digital I/O", "Turn off digital output synchronized with motion (P word)",
     "M63 P0  (turn off output 0 at next motion start)"),
    ("M64", "Digital I/O", "Turn on digital output immediately (P word)",
     "M64 P1  (turn on output 1 right now)"),
    ("M65", "Digital I/O", "Turn off digital output immediately (P word)",
     "M65 P1  (turn off output 1 right now)"),
    ("M66", "Digital I/O", "Wait for input — pause until digital/analog input condition met",
     "M66 P0 L0 Q5  (wait up to 5s for input 0 to go HIGH)"),
    ("M67", "Analog I/O", "Set analog output synchronized with motion (E word = value)",
     "M67 E0 Q0.5  (set analog out 0 to 0.5 at motion)"),
    ("M68", "Analog I/O", "Set analog output immediately (E word = value)",
     "M68 E0 Q1.0  (set analog out 0 to 1.0 immediately)"),
    # --- Path/Mode ---
    ("M70", "Save/Restore", "Save modal state — push current G-code state to stack",
     "M70  (save all modal codes before subroutine)"),
    ("M71", "Save/Restore", "Invalidate stored state — mark saved state as invalid",
     "M71  (discard saved state)"),
    ("M72", "Save/Restore", "Restore modal state — pop and restore saved state",
     "M72  (restore modes saved by M70)"),
    ("M73", "Save/Restore", "Save and auto-restore modal state at program end",
     "M73  (save state, auto-restore on M2/M30)"),
    # --- Subroutines ---
    ("M98", "Subroutines", "Call subprogram (some implementations)",
     "M98 P1000  (call subroutine O1000)"),
    ("M99", "Subroutines", "Return from subprogram / program repeat",
     "M99  (return to calling program)"),
    # --- User-defined ---
    ("M100-M199", "User Defined", "User-defined M-codes — execute external scripts via M1xx",
     "M101 P5  (run /usr/bin/M101 with arg 5)"),
]

OTHER_CODES: List[GCodeEntry] = [
    # --- O-codes (program flow) ---
    ("O sub/endsub", "Flow Control", "Define a named or numbered subroutine",
     "O100 sub\n  G1 X#1 F0.005\nO100 endsub"),
    ("O call", "Flow Control", "Call a subroutine by name or number",
     "O100 call [1.5]  (call sub 100 with arg 1.5)"),
    ("O return", "Flow Control", "Return from subroutine (optional return value)",
     "O100 return [#5]  (return parameter 5 value)"),
    ("O if/elseif/else/endif", "Flow Control", "Conditional execution block",
     "O101 if [#1 GT 1.0]\n  G1 X#1\nO101 else\n  G1 X1.0\nO101 endif"),
    ("O while/endwhile", "Flow Control", "While loop — repeat while condition is true",
     "O102 while [#1 LT 10]\n  #1 = [#1 + 1]\n  G1 Z[-#1 * 0.1]\nO102 endwhile"),
    ("O do/while", "Flow Control", "Do-while loop — execute at least once",
     "O103 do\n  G1 Z-0.1\n  #1 = [#1 + 1]\nO103 while [#1 LT 5]"),
    ("O repeat/endrepeat", "Flow Control", "Repeat block a fixed number of times",
     "O104 repeat [5]\n  G1 Z-0.1\n  G0 Z0.05\nO104 endrepeat"),
    ("O break", "Flow Control", "Break out of while/do/repeat loop",
     "O105 if [#1 GT 5]\n  O102 break\nO105 endif"),
    ("O continue", "Flow Control", "Skip to next iteration of loop",
     "O106 if [#1 EQ 3]\n  O102 continue\nO106 endif"),
    # --- Special letters ---
    ("F", "Feed/Speed", "Feed rate — units depend on G93/G94/G95 mode",
     "G95 F0.005  (0.005 in/rev in G95 mode)\nG94 F10.0  (10 in/min in G94 mode)"),
    ("S", "Feed/Speed", "Spindle speed — RPM (G97) or surface speed (G96)",
     "G97 S800  (800 RPM)\nG96 S400  (400 surface ft/min)"),
    ("T", "Tool Select", "Tool select — Tnn or Tnnnn (tool and offset number)",
     "T0101  (select tool 1, offset 1)\nT0300  (select tool 3, no offset)"),
    ("N", "Line Number", "Line number — optional label for program lines",
     "N100 G1 X1.0 Z-0.5 F0.005  (labeled line 100)"),
    ("H", "Tool Length", "Tool length offset number (used with G43)",
     "G43 H2  (apply tool 2 length offset)"),
    ("D", "Cutter Comp", "Cutter compensation diameter number",
     "G42 D1  (comp right using tool 1 nose radius)"),
    ("P", "Parameter", "Dwell time, subroutine number, or parameter value",
     "G4 P1.0  (dwell 1 second)\nG82 Z-0.5 P0.5  (dwell 0.5s at bottom)"),
    ("Q", "Parameter", "Peck depth (drilling) or path tolerance (G64)",
     "G83 Z-2.0 Q0.25  (peck 0.25\" per pass)\nG64 P0.001 Q0.001  (blend tolerance)"),
    ("R", "Parameter", "Arc radius, retract level, or cycle parameter",
     "G2 X1.0 Z-0.5 R0.5  (arc with 0.5\" radius)\nG81 Z-0.5 R0.1  (retract to R0.1)"),
    ("L", "Parameter", "Loop count for canned cycles, or G10 sub-function",
     "G81 Z-0.5 R0.1 L3  (drill 3 times)\nG10 L20 P1 X2.0  (L20 = set from current)"),
    ("I", "Arc Center", "Arc center X offset (incremental from start, diameter on lathe)",
     "G2 X1.0 Z-0.5 I-0.5 K0.0  (center is 0.25\" radius left of start)"),
    ("J", "Arc Center", "Arc center Y offset (incremental from start)",
     "G2 X1.0 Y0.5 J0.5  (mill: center 0.5\" above start)"),
    ("K", "Arc Center", "Arc center Z offset (incremental from start)",
     "G2 X1.0 Z-0.5 I0.0 K-0.25  (center 0.25\" below start in Z)"),
    ("X", "Axis", "X axis position (diameter on lathe)",
     "G1 X1.5  (move to 1.5\" diameter)"),
    ("Y", "Axis", "Y axis position",
     "G1 Y0.5  (mill: move to Y=0.5\")"),
    ("Z", "Axis", "Z axis position",
     "G1 Z-1.0  (move to Z=-1.0\")"),
    ("A", "Axis", "A rotary axis position",
     "G1 A90.0  (rotate A axis to 90 degrees)"),
    ("B", "Axis", "B rotary axis position",
     "G1 B45.0  (rotate B axis to 45 degrees)"),
    ("C", "Axis", "C rotary axis position",
     "G1 C180.0  (rotate C axis to 180 degrees)"),
    ("U", "Axis", "U linear axis position (parallel to X)",
     "G1 U0.5  (move U axis to 0.5\")"),
    ("V", "Axis", "V linear axis position (parallel to Y)",
     "G1 V0.5  (move V axis to 0.5\")"),
    ("W", "Axis", "W linear axis position (parallel to Z)",
     "G1 W-0.1  (move W axis to -0.1\")"),
    # --- Comments ---
    ("( )", "Comments", "Inline comment — text between parentheses is ignored",
     "G1 X1.0 (rough pass 1) Z-0.5 F0.005"),
    (";", "Comments", "End-of-line comment — everything after semicolon is ignored",
     "G1 X1.0 Z-0.5 F0.005 ; rough pass 1"),
    # --- Parameters ---
    ("#", "Parameters", "Named or numbered parameter — #100, #<name>, #<_global>",
     "#100 = 1.5  (set param 100)\nG1 X#100  (use param as X value)"),
    ("=", "Parameters", "Parameter assignment — #100 = 1.5",
     "#<depth> = 0.5\n#<_stock_dia> = 2.0  (global parameter)"),
]


def get_all_codes() -> List[GCodeEntry]:
    """Return all codes combined (G + M + Other) for unified search."""
    return G_CODES + M_CODES + OTHER_CODES
